### ISSUE TITLE
Convert Adobe Cube LUT files (.cube) to color lookup table images png

### ISSUE THREAD

**Issue by LeeCenY** [YuAo/ColorLookupTable2Cube#1]
Is it ok?

**Comment by YuAo** [comment]
There is no plan of adding this feature. I think you can do that using Photoshop.

**Comment by pluginslab** [comment]
How about transforming the .cube file into a MTLTextureDescriptor and then into an MTIImage? Is that possible?

**Comment by pluginslab** [comment]
Ok, I guess if I do `MTIImage(texture: texture!, alphaType: .alphaIsOne)` and the texture is a MTLTexture, I can us this as a lookupImage for the LUT filter. So this way I can go from .CUBE to a rendered LUT image.

**Comment by YuAo** [comment]
@pluginslab I'm not sure what you mean.

It is recommend to convert the `.cube` to LUT image in an offline process. The `cube` file is text based which is generally less efficient to load and decode compares to binary representations like `png`/`bmp` image files.

If you do want to load `cube` files you should follow the adobe cube file specification and decode and arrange the LUT as a bitmap then use `MTIImage(bitmapData:....)` to load the data as a `MTIImage`.
https://wwwimages2.adobe.com/content/dam/acom/en/products/speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf

**Comment by pluginslab** [comment]
Right, with png/bmp it's faster. I did this: 

```
let url = Bundle.main.url(forResource: self.rawValue, withExtension: ".cube")!
let texture = AdobeLUTParser.texture(withContentsOf: url, device: MTLCreateSystemDefaultDevice()!)
let image = MTIImage(texture: texture!, alphaType: .alphaIsOne)            
return image
```

But it is way slower than with a png/bmp. I was looking for a solution where I'd add a .cube file and get the PNG, the reverse of what you're doing here. I can easily generate .cube from another software that I use to create templates, so I was thinking if I can escape this additional step and just add the .cube.

**Comment by YuAo** [comment]
You can generate the LUT image by applying the `cube` using ColorLookupFilter to an identity LUT image.

**Comment by pluginslab** [comment]
Wondering if that's even more work for the app than just load the modified identity LUT image previously done in Photoshop. Will test it. Thanks for the feedback.

**Comment by YuAo** [comment]
You may choose to create a LUT cache so the app needs to do that only once.

**Comment by pluginslab** [comment]
Exactly, I just need to figure out what the LUT_3D_SIZE means for the conversion. 

Thanks for the help!

**Comment by ai2ys** [comment]
> @pluginslab I'm not sure what you mean.
> 
> It is recommend to convert the `.cube` to LUT image in an offline process. The `cube` file is text based which is generally less efficient to load and decode compares to binary representations like `png`/`bmp` image files.
> 
> If you do want to load `cube` files you should follow the adobe cube file specification and decode and arrange the LUT as a bitmap then use `MTIImage(bitmapData:....)` to load the data as a `MTIImage`. https://wwwimages2.adobe.com/content/dam/acom/en/products/speedgrade/cc/pdfs/cube-lut-specification-1.0.pdf

This link does not work anymore. Can someone tell me where the latest cube LUT specification can be downloaded.

**Comment by TechySachin0098** [comment]
Hey i am creating a layer of the color of an image and adding the RGB values into a .CUBE file but when i am applying this cube file in photoshop on any image the color are not appearing rightlyor not matching 
, how to correct this  ?
